name: update docker images descriptions
on:
  workflow_dispatch: {}

  push:
    tags:
      - 'release-*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-update-docker-images-descriptions
  cancel-in-progress: false

jobs:

  update-metadata:
    name: Update Docker Hub metadata
    runs-on: ubuntu-latest
    environment: release

    strategy:
      matrix:
        include:
          - repository: tiendil/keycloak-simple
            readme: ./README.md
            short: Keycloak Simple â€” customized Keycloak docker container for Tiendil's personal projects.
    steps:
      - uses: actions/checkout@v4
      - name: Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v5
        with:
          username: tiendil
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ matrix.repository }}
          short-description: ${{ matrix.short }}
          readme-filepath: ${{ matrix.readme }}
          enable-url-completion: true
